#!/bin/sh

usage="$(basename $0) [-h] [-v version] [-e event] [-P path] [-S source path] -- AnyStor FCE script

where:
    -h  show this help text
    -v  version
    -e  event
    -P  path
    -S  source path for events like rename/move
    -u  username
    -p  pid
    -i  event ID
"

while getopts ':hs:v:e:P:S:u:p:i:' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    v) version=$OPTARG
       ;;
    e) event=$OPTARG
       ;;
    P) path=$OPTARG
       ;;
    S) srcpath=$OPTARG
       ;;
    u) user=$OPTARG
       ;;
    p) pid=$OPTARG
       ;;
    i) evid=$OPTARG
       ;;
    ?) printf "illegal option: '%s'\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))

if [ "$event" == "FCE_LOGIN" ]; then
    eflowdctl event create \
        --from="${HOSTNAME%%.*}" --code="AFP_LOGIN" \
        --msg="User \"${user}\" has logged in via AFP."
fi
