---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - install-pkgs
    - prepare-brick
    - selinux
    - iptables

- hosts: all
  become: yes
  become_method: sudo
  serial: 1
  roles:
    - compile-gluster
    - service

- hosts: origin
  become: yes
  become_method: sudo
  roles:
    - cluster
