meta:
- desc: |
   randomly kill and revive osd
   small chance to increase the number of pgs
overrides:
  ceph:
    log-ignorelist:
    - but it is still running
    - wrongly marked me down
    - objects unfound and apparently lost
    - log bound mismatch
tasks:
- parallel:
  - stress-tasks
stress-tasks:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgpnum_fix: 1
    chance_thrash_cluster_full: 0
    chance_thrash_pg_upmap: 0
    chance_thrash_pg_upmap_items: 0
    disable_objectstore_tool_tests: true
    chance_force_recovery: 0
    aggressive_pg_num_changes: false
- print: "**** done thrashosds 3-thrash"
